export const TechnicalIndicatorDefaultPreferences = {
	ema: true,
	sma: true,
	wma: false,
	rsi: true,
	macd: true,
	bollingerBands: true,
	atr: true,
	volatility: false,
	stdDev: true,
	slope: false,
	dmi: true,
	adx: true,
	cci: false,
	sar: false,
	beta: false,
	stochastic: false,
	stochasticRSI: false,
	averageVolume: false,
	averageVolumeByPrice: false,
	splitAdjusted: false,
};
