export const TechnicalIndicatorPreferences = {
	ema: true,
	sma: true,
	wma: false,
	rsi: true,
	macd: true,
	bollingerBands: true,
	atr: true,
	volatility: true,
	stdDev: true,
	slope: false,
	dmi: true,
	adx: true,
	cci: true,
	sar: false,
	beta: false,
	stochastic: true,
	stochasticRSI: true,
	averageVolume: true,
	averageVolumeByPrice: true,
	splitAdjusted: true,
};
